//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenevolesProjet
    {
        public int codeBenevoleProjet { get; set; }
        public int codeProjet { get; set; }
        public int codeBenevole { get; set; }
    
        public virtual Benevole Benevole { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
