//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benevole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benevole()
        {
            this.BenevolesProjets = new HashSet<BenevolesProjet>();
        }
    
        public int codeBenevole { get; set; }
        public Nullable<System.DateTime> dateAdhesionBenevole { get; set; }
        public Nullable<int> codeUser { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenevolesProjet> BenevolesProjets { get; set; }
    }
}
