//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampagneLeveeFond
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampagneLeveeFond()
        {
            this.Dons = new HashSet<Don>();
        }
    
        public int codeCampagneLeveeFond { get; set; }
        public string titreCampagneLeveeFond { get; set; }
        public Nullable<System.DateTime> dateDebutCampagneLeveeFond { get; set; }
        public Nullable<System.DateTime> dateFinCampagneLeveeFond { get; set; }
        public Nullable<decimal> montantCibleCampagneLeveeFond { get; set; }
        public Nullable<decimal> totalRealiseCampagneLeveeFond { get; set; }
        public Nullable<int> codeProjet { get; set; }
    
        public virtual Projet Projet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don> Dons { get; set; }

    }
}
