//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteRendu
    {
        public int codeCompteRendu { get; set; }
        public string frequenceCompteRendu { get; set; }
        public Nullable<System.DateTime> dateCompteRendu { get; set; }
        public Nullable<int> codeProjetCompteRendu { get; set; }
    
        public virtual ProjetCompteRendu ProjetCompteRendu { get; set; }
    }
    public enum Frequence
    {
        Quotidienne,
        Hebdomadaire,
        DeuxSemaines, 
        Mois
    }
}
