//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Don
    {
        public int codeDon { get; set; }
        [Required]
        public Nullable<decimal> montantDon { get; set; }
        public string typePaiementDon { get; set; }
        public string nomDonateur { get; set; }
        public string prenomDonateur { get; set; }
        public Nullable<System.DateTime> dateDon { get; set; }
        public string emailDonateur { get; set; }
        public string numPhoneDonateur { get; set; }
        public string adresseDonateur { get; set; }
        public string villeDonateur { get; set; }
        public string cpDonateur { get; set; }
        public string PaysDonateur { get; set; }
        public Nullable<int> codeCampagneLeveeFond { get; set; }
    
        public virtual CampagneLeveeFond CampagneLeveeFond { get; set; }
    }
}
