//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Fichier
    {
        public int codefichier { get; set; }
        public string nomAltFichier { get; set; }
        [DisplayName("Téléversé un fichier")]
        public string linkFichier { get; set; }
        public Nullable<int> codeProjet { get; set; }
    
        public virtual Projet Projet { get; set; }
        public HttpPostedFileBase FichierFile { get; set; }
    }
}
