//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membre()
        {
            this.CarteBancaires = new HashSet<CarteBancaire>();
            this.MembresProjets = new HashSet<MembresProjet>();
        }
    
        public int codeMembre { get; set; }
        public Nullable<System.DateTime> dateAdhesionMembre { get; set; }
        public string nomStatut { get; set; }
        public Nullable<int> codeUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarteBancaire> CarteBancaires { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembresProjet> MembresProjets { get; set; }
    }
    public enum Staut
    {
       Actif,
       Terminé,
       AttenteCotisation,
       Gelé
    }
}
