//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembresProjet
    {
        public int codeMembreProjet { get; set; }
        public Nullable<bool> responsableProjet { get; set; }
        public Nullable<int> codeMembre { get; set; }
        public Nullable<int> codeProjet { get; set; }
    
        public virtual Membre Membre { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
