//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetGo_dbEntities : DbContext
    {
        public ProjetGo_dbEntities()
            : base("name=ProjetGo_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Benevole> Benevoles { get; set; }
        public virtual DbSet<BenevolesProjet> BenevolesProjets { get; set; }
        public virtual DbSet<CampagneLeveeFond> CampagneLeveeFonds { get; set; }
        public virtual DbSet<CarteBancaire> CarteBancaires { get; set; }
        public virtual DbSet<CompteRendu> CompteRendus { get; set; }
        public virtual DbSet<Don> Dons { get; set; }
        public virtual DbSet<Fichier> Fichiers { get; set; }
        public virtual DbSet<Membre> Membres { get; set; }
        public virtual DbSet<MembreRecu> MembreRecus { get; set; }
        public virtual DbSet<MembresProjet> MembresProjets { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<ProjetCompteRendu> ProjetCompteRendus { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
