//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetCompteRendu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjetCompteRendu()
        {
            this.CompteRendus = new HashSet<CompteRendu>();
            this.Projets = new HashSet<Projet>();
        }
    
        public int codeProjetCompteRendu { get; set; }
        public string realisationsCompletees { get; set; }
        public Nullable<System.DateTime> dateFinEstimee { get; set; }
        public Nullable<System.DateTime> echeancier { get; set; }
        public Nullable<decimal> totalFondsCollectes { get; set; }
        public decimal totalDepenses { get; set; }
        public string etatAvancement { get; set; }
        public string etatRisques { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompteRendu> CompteRendus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet> Projets { get; set; }
    }
    public enum Avancement
    {
        Vert, 
        Jaune, 
        Rouge
    }
}
