//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Benevoles = new HashSet<Benevole>();
            this.Membres = new HashSet<Membre>();
        }
    
        public int codeUser { get; set; }
        public string nomUser { get; set; }
        public string prenomUser { get; set; }
        public string niveauAccesUser { get; set; }
        public string emailUser { get; set; }
        public string passwordUser { get; set; }
        public string numPhoneUser { get; set; }
        public string adresseUser { get; set; }
        public string villeUser { get; set; }
        public string cpUser { get; set; }
        public string paysUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benevole> Benevoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membre> Membres { get; set; }
    }
}
